### ISSUE TITLE
请问有没有原作业（原本发布的js版本）的备份

### ISSUE THREAD

**Issue by Da1sypetals** [vonbrank/GAMES202-Assignment-Framework-with-TypeScript-Support#1]
请问有没有原作业（原本发布的js版本）的备份？求一份复制，谢谢

**Comment by vonbrank** [comment]
原 JavaScript 版本上传到蓝奏云了，可以看一下：
- 地址：https://wwit.lanzout.com/b01wvxvji
- 密码：`4sup`

不过这些其实在 [课程官网](https://sites.cs.ucsb.edu/~lingqi/teaching/games202.html) 的 [作业汇总](https://games-cn.org/forums/topic/games202zuoyehuizong/) 其实都能找到。
